# config.yml

base_domain_prefix: "https://trgoals"
domain_start: 1393
domain_end: 2100

proxy_base: "https://dawn-salad-c3ef.aykara463.workers.dev/?url="

logo_url: "https://i.hizliresim.com/ska5t9e.jpg"
group_title: "GOALS IPTV"

channels:
  yayinzirve: "beIN Sports 1 ☪️"
  yayininat: "beIN Sports 1 ⭐"
  yayin1: "beIN Sports 1 ♾️"
  yayinb2: "beIN Sports 2"
  yayinb3: "beIN Sports 3"
  yayinb4: "beIN Sports 4"
  yayinb5: "beIN Sports 5"
  yayinbm1: "beIN Sports 1 Max"
  yayinbm2: "beIN Sports 2 Max"
  yayinss: "Saran Sports 1"
  yayinss2: "Saran Sports 2"
  yayint1: "Tivibu Sports 1"
  yayint2: "Tivibu Sports 2"
  yayint3: "Tivibu Sports 3"
  yayint4: "Tivibu Sports 4"
  yayinsmarts: "Smart Sports"
  yayinsms2: "Smart Sports 2"
  yayintrtspor: "TRT Spor"
  yayintrtspor2: "TRT Spor 2"
  yayinas: "A Spor"
  yayinatv: "ATV"
  yayintv8: "TV8"
  yayintv85: "TV8.5"
  yayinnbatv: "NBA TV"
  yayinex1: "Tâbii 1"
  yayinex2: "Tâbii 2"
  yayinex3: "Tâbii 3"
  yayinex4: "Tâbii 4"
  yayinex5: "Tâbii 5"
  yayinex6: "Tâbii 6"
  yayinex7: "Tâbii 7"
  yayinex8: "Tâbii 8"
